# 해당 파일은 Portainer에서 사용되는 Paxi Stack을 복사 붙여넣기 한 파일로, 참고용입니다.
# 해당 파일을 수정해도 반영되지 않습니다. Portainer에 직접 들어가 수정해야 합니다.
version: '3.3'
services:
  dev:
    image: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com/popo-admin-web:latest
    ports:
      - 5001:3001
    deploy:
      placement:
        constraints:
          - node.role == manager
  prod:
    # Production 버전은 수동으로 변경해줘야 합니다.
    image: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com/popo-admin-web:vX.X.X
    ports:
      - 3001:3001
    deploy:
      placement:
        constraints:
          - node.role == manager
